server:
  port: 9090

spring:
  application:
    name: msvc-course
  datasource:
    drive-class-name: org.postgresql.Drive
    url: jdbc:postgresql://localhost:5432/coursesDb
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  config:
#    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka